spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: password
    driverClassName: oracle.jdbc.driver.OracleDriver